<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="emf"
    nsURI="http://www.activiti.com/repo/datadictionary" nsPrefix="datadictionary">
  <eClassifiers xsi:type="ecore:EClass" name="EMFClass" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfName" eType="#//QName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfProperties" upperBound="-1"
        eType="#//EMFProperty" containment="true" eOpposite="#//EMFProperty/emfContainerClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfSuperClass" eType="#//EMFClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfAssociations" upperBound="-1"
        eType="#//EMFAssociation" containment="true" eOpposite="#//EMFAssociation/emfContainerClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfContainerClass" eType="#//EMFClass"
        changeable="false" transient="true" eOpposite="#//EMFClass/emfProperties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfType" eType="#//EMFPropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfProtected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfMandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfMultiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfIndexed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfStoredInIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfTokenisedInIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfIndexAtomically" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFAspect" eSuperTypes="#//EMFClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFAssociation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfContainerClass" eType="#//EMFClass"
        changeable="false" transient="true" eOpposite="#//EMFClass/emfAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfProtected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfMandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfMultiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfRequiredToClasses" upperBound="-1"
        eType="#//EMFClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFChildAssociation" eSuperTypes="#//EMFAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfDefaultType" eType="#//EMFType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFPropertyType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" eType="#//QName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfAnalyserClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFType" eSuperTypes="#//EMFClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfOrderedChildren" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfDefaultAspects" upperBound="-1"
        eType="#//EMFAspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfStrict" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="QName" instanceClassName="com.activiti.repo.ref.QName"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFNamespaceURI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfPrefixes" upperBound="-1"
        eType="#//EMFNamespacePrefix" eOpposite="#//EMFNamespacePrefix/emfURI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFNamespacePrefix">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emfPrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfURI" lowerBound="1"
        eType="#//EMFNamespaceURI" eOpposite="#//EMFNamespaceURI/emfPrefixes"/>
  </eClassifiers>
</ecore:EPackage>
