--
-- Title:      Update ACT_HI_PROCINST table. Create normal name for unique constraint on PROC_INST_ID_
-- Database:   DB2
--
-- Title:      Update ALF_ACTIVITY_FEED table. Detete all records with activity_format != "json". Remove column ACTIVITY_FORMAT
-- Database:   Generic
-- Since:      V4.1 Schema 5119
-- Author:     Alex Malinovsky
--
-- Please contact support@alfresco.com if you need assistance with the upgrade.
--
-- MNT-8983: 'Could not load activities list' in My/Site Activities dashlets after upgrade if activities were generated on 3.4.x
-- ALF-17493 : Remove alf_activity_feed.activity_format.
--
-- Record script finish
--

DELETE FROM alf_activity_feed WHERE activity_format <> 'json';

rename ALF_ACTIVITY_FEED to t_ALF_ACTIVITY_FEED;

DROP INDEX feed_activityformat_idx;
DROP INDEX feed_feeduserid_idx;
DROP INDEX feed_postdate_idx;
DROP INDEX feed_postuserid_idx;
DROP INDEX feed_sitenetwork_idx;

--ASSIGN:activity_next_id=activity_max_id
SELECT CASE WHEN MAX(id) IS NOT NULL THEN MAX(id)+1 ELSE 1 END AS activity_max_id FROM t_ALF_ACTIVITY_FEED;

CREATE TABLE alf_activity_feed
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH ${activity_next_id}),
    post_id BIGINT,
    post_date TIMESTAMP NOT NULL,
    activity_summary VARCHAR(4096),
    feed_user_id VARCHAR(1020),
    activity_type VARCHAR(1020) NOT NULL,
    site_network VARCHAR(1020),
    app_tool VARCHAR(144),
    post_user_id VARCHAR(1020) NOT NULL,
    feed_date TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX feed_postdate_idx ON ALF_ACTIVITY_FEED (post_date);
CREATE INDEX feed_postuserid_idx ON ALF_ACTIVITY_FEED (post_user_id);
CREATE INDEX feed_feeduserid_idx ON ALF_ACTIVITY_FEED (feed_user_id);
CREATE INDEX feed_sitenetwork_idx ON ALF_ACTIVITY_FEED (site_network);

insert into ALF_ACTIVITY_FEED
(id, post_id, post_date, activity_summary, feed_user_id, activity_type, site_network, app_tool, post_user_id, feed_date)
(
    select
       id, post_id, post_date, activity_summary, feed_user_id, activity_type, site_network, app_tool, post_user_id, feed_date
    from
       t_ALF_ACTIVITY_FEED
);

drop table t_ALF_ACTIVITY_FEED;

--
-- Record script finish
--
DELETE FROM alf_applied_patch WHERE id = 'patch.db-V4.1-drop-activiti-feed-format';
INSERT INTO alf_applied_patch
  (id, description, fixes_from_schema, fixes_to_schema, applied_to_schema, target_schema, applied_on_date, applied_to_server, was_executed, succeeded, report)
  VALUES
  (
    'patch.db-V4.1-drop-activiti-feed-format', 'Manually executed script upgrade V4.1: Update ALF_ACTIVITY_FEED table. Remove column ACTIVITY_FORMAT',
    0, 6025, -1, 6026, null, 'UNKNOWN', ${TRUE}, ${TRUE}, 'Script completed'
  );