//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Alfresco.RepositoryWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RepositoryServiceSoapBinding", Namespace="http://www.alfresco.org/ws/service/repository/1.0")]
    public partial class RepositoryService : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback createStoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStoresOperationCompleted;
        
        private QueryConfiguration queryConfigurationValueField;
        
        private System.Threading.SendOrPostCallback queryOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryParentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryAssociatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchMoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback describeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RepositoryService() {
            this.Url = global::Alfresco.Properties.Settings.Default.Alfresco_RepositoryWebService_RepositoryService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public QueryConfiguration QueryConfigurationValue {
            get {
                return this.queryConfigurationValueField;
            }
            set {
                this.queryConfigurationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event createStoreCompletedEventHandler createStoreCompleted;
        
        /// <remarks/>
        public event getStoresCompletedEventHandler getStoresCompleted;
        
        /// <remarks/>
        public event queryCompletedEventHandler queryCompleted;
        
        /// <remarks/>
        public event queryChildrenCompletedEventHandler queryChildrenCompleted;
        
        /// <remarks/>
        public event queryParentsCompletedEventHandler queryParentsCompleted;
        
        /// <remarks/>
        public event queryAssociatedCompletedEventHandler queryAssociatedCompleted;
        
        /// <remarks/>
        public event fetchMoreCompletedEventHandler fetchMoreCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event describeCompletedEventHandler describeCompleted;
        
        /// <remarks/>
        public event getCompletedEventHandler getCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/createStore", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("createStoreReturn")]
        public Store createStore(StoreEnum scheme, string address) {
            object[] results = this.Invoke("createStore", new object[] {
                        scheme,
                        address});
            return ((Store)(results[0]));
        }
        
        /// <remarks/>
        public void createStoreAsync(StoreEnum scheme, string address) {
            this.createStoreAsync(scheme, address, null);
        }
        
        /// <remarks/>
        public void createStoreAsync(StoreEnum scheme, string address, object userState) {
            if ((this.createStoreOperationCompleted == null)) {
                this.createStoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateStoreOperationCompleted);
            }
            this.InvokeAsync("createStore", new object[] {
                        scheme,
                        address}, this.createStoreOperationCompleted, userState);
        }
        
        private void OncreateStoreOperationCompleted(object arg) {
            if ((this.createStoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createStoreCompleted(this, new createStoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/getStores", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getStoresReturn")]
        public Store[] getStores() {
            object[] results = this.Invoke("getStores", new object[0]);
            return ((Store[])(results[0]));
        }
        
        /// <remarks/>
        public void getStoresAsync() {
            this.getStoresAsync(null);
        }
        
        /// <remarks/>
        public void getStoresAsync(object userState) {
            if ((this.getStoresOperationCompleted == null)) {
                this.getStoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStoresOperationCompleted);
            }
            this.InvokeAsync("getStores", new object[0], this.getStoresOperationCompleted, userState);
        }
        
        private void OngetStoresOperationCompleted(object arg) {
            if ((this.getStoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStoresCompleted(this, new getStoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryConfigurationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/query", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult query(Store store, [System.Xml.Serialization.XmlElementAttribute("query")] Query query1, bool includeMetaData) {
            object[] results = this.Invoke("query", new object[] {
                        store,
                        query1,
                        includeMetaData});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void queryAsync(Store store, Query query1, bool includeMetaData) {
            this.queryAsync(store, query1, includeMetaData, null);
        }
        
        /// <remarks/>
        public void queryAsync(Store store, Query query1, bool includeMetaData, object userState) {
            if ((this.queryOperationCompleted == null)) {
                this.queryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryOperationCompleted);
            }
            this.InvokeAsync("query", new object[] {
                        store,
                        query1,
                        includeMetaData}, this.queryOperationCompleted, userState);
        }
        
        private void OnqueryOperationCompleted(object arg) {
            if ((this.queryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCompleted(this, new queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryConfigurationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/queryChildren", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult queryChildren(Reference node) {
            object[] results = this.Invoke("queryChildren", new object[] {
                        node});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void queryChildrenAsync(Reference node) {
            this.queryChildrenAsync(node, null);
        }
        
        /// <remarks/>
        public void queryChildrenAsync(Reference node, object userState) {
            if ((this.queryChildrenOperationCompleted == null)) {
                this.queryChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryChildrenOperationCompleted);
            }
            this.InvokeAsync("queryChildren", new object[] {
                        node}, this.queryChildrenOperationCompleted, userState);
        }
        
        private void OnqueryChildrenOperationCompleted(object arg) {
            if ((this.queryChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryChildrenCompleted(this, new queryChildrenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryConfigurationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/queryParents", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult queryParents(Reference node) {
            object[] results = this.Invoke("queryParents", new object[] {
                        node});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void queryParentsAsync(Reference node) {
            this.queryParentsAsync(node, null);
        }
        
        /// <remarks/>
        public void queryParentsAsync(Reference node, object userState) {
            if ((this.queryParentsOperationCompleted == null)) {
                this.queryParentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryParentsOperationCompleted);
            }
            this.InvokeAsync("queryParents", new object[] {
                        node}, this.queryParentsOperationCompleted, userState);
        }
        
        private void OnqueryParentsOperationCompleted(object arg) {
            if ((this.queryParentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryParentsCompleted(this, new queryParentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryConfigurationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/queryAssociated", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult queryAssociated(Reference node, [System.Xml.Serialization.XmlElementAttribute("association")] Association[] association) {
            object[] results = this.Invoke("queryAssociated", new object[] {
                        node,
                        association});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void queryAssociatedAsync(Reference node, Association[] association) {
            this.queryAssociatedAsync(node, association, null);
        }
        
        /// <remarks/>
        public void queryAssociatedAsync(Reference node, Association[] association, object userState) {
            if ((this.queryAssociatedOperationCompleted == null)) {
                this.queryAssociatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAssociatedOperationCompleted);
            }
            this.InvokeAsync("queryAssociated", new object[] {
                        node,
                        association}, this.queryAssociatedOperationCompleted, userState);
        }
        
        private void OnqueryAssociatedOperationCompleted(object arg) {
            if ((this.queryAssociatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryAssociatedCompleted(this, new queryAssociatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/fetchMore", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult fetchMore(string querySession) {
            object[] results = this.Invoke("fetchMore", new object[] {
                        querySession});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void fetchMoreAsync(string querySession) {
            this.fetchMoreAsync(querySession, null);
        }
        
        /// <remarks/>
        public void fetchMoreAsync(string querySession, object userState) {
            if ((this.fetchMoreOperationCompleted == null)) {
                this.fetchMoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchMoreOperationCompleted);
            }
            this.InvokeAsync("fetchMore", new object[] {
                        querySession}, this.fetchMoreOperationCompleted, userState);
        }
        
        private void OnfetchMoreOperationCompleted(object arg) {
            if ((this.fetchMoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchMoreCompleted(this, new fetchMoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/update", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateReturn")]
        public UpdateResult[] update(CML statements) {
            object[] results = this.Invoke("update", new object[] {
                        statements});
            return ((UpdateResult[])(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(CML statements) {
            this.updateAsync(statements, null);
        }
        
        /// <remarks/>
        public void updateAsync(CML statements, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        statements}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/describe", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("describeReturn")]
        public NodeDefinition[] describe(Predicate items) {
            object[] results = this.Invoke("describe", new object[] {
                        items});
            return ((NodeDefinition[])(results[0]));
        }
        
        /// <remarks/>
        public void describeAsync(Predicate items) {
            this.describeAsync(items, null);
        }
        
        /// <remarks/>
        public void describeAsync(Predicate items, object userState) {
            if ((this.describeOperationCompleted == null)) {
                this.describeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescribeOperationCompleted);
            }
            this.InvokeAsync("describe", new object[] {
                        items}, this.describeOperationCompleted, userState);
        }
        
        private void OndescribeOperationCompleted(object arg) {
            if ((this.describeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.describeCompleted(this, new describeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/get", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getReturn")]
        public Node[] get(Predicate @where) {
            object[] results = this.Invoke("get", new object[] {
                        @where});
            return ((Node[])(results[0]));
        }
        
        /// <remarks/>
        public void getAsync(Predicate @where) {
            this.getAsync(@where, null);
        }
        
        /// <remarks/>
        public void getAsync(Predicate @where, object userState) {
            if ((this.getOperationCompleted == null)) {
                this.getOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationCompleted);
            }
            this.InvokeAsync("get", new object[] {
                        @where}, this.getOperationCompleted, userState);
        }
        
        private void OngetOperationCompleted(object arg) {
            if ((this.getCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCompleted(this, new getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/headers/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.alfresco.org/ws/service/repository/1.0", IsNullable=false)]
    public partial class QueryConfiguration : System.Web.Services.Protocols.SoapHeader {
        
        private int fetchSizeField;
        
        public QueryConfiguration() {
            this.fetchSizeField = 500;
        }
        
        /// <remarks/>
        public int fetchSize {
            get {
                return this.fetchSizeField;
            }
            set {
                this.fetchSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Node {
        
        private Reference referenceField;
        
        private string typeField;
        
        private string[] aspectsField;
        
        private NamedValue[] propertiesField;
        
        /// <remarks/>
        public Reference reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aspects")]
        public string[] aspects {
            get {
                return this.aspectsField;
            }
            set {
                this.aspectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties")]
        public NamedValue[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParentReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Reference {
        
        private Store storeField;
        
        private string uuidField;
        
        private string pathField;
        
        public Reference() {
            this.pathField = "/";
        }
        
        /// <remarks/>
        public Store store {
            get {
                return this.storeField;
            }
            set {
                this.storeField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("/")]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Store {
        
        private StoreEnum schemeField;
        
        private string addressField;
        
        /// <remarks/>
        public StoreEnum scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum StoreEnum {
        
        /// <remarks/>
        workspace,
        
        /// <remarks/>
        versionStore,
        
        /// <remarks/>
        user,
        
        /// <remarks/>
        search,
        
        /// <remarks/>
        http,
        
        /// <remarks/>
        system,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ParentReference : Reference {
        
        private string associationTypeField;
        
        private string childNameField;
        
        /// <remarks/>
        public string associationType {
            get {
                return this.associationTypeField;
            }
            set {
                this.associationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string childName {
            get {
                return this.childNameField;
            }
            set {
                this.childNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class NamedValue {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class NodeDefinition {
        
        private ClassDefinition typeField;
        
        private ClassDefinition[] aspectsField;
        
        /// <remarks/>
        public ClassDefinition type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aspects")]
        public ClassDefinition[] aspects {
            get {
                return this.aspectsField;
            }
            set {
                this.aspectsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ClassDefinition {
        
        private string nameField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string superClassField;
        
        private bool isAspectField;
        
        private PropertyDefinition[] propertiesField;
        
        private AssociationDefinition[] associationsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string superClass {
            get {
                return this.superClassField;
            }
            set {
                this.superClassField = value;
            }
        }
        
        /// <remarks/>
        public bool isAspect {
            get {
                return this.isAspectField;
            }
            set {
                this.isAspectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties", IsNullable=true)]
        public PropertyDefinition[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associations", IsNullable=true)]
        public AssociationDefinition[] associations {
            get {
                return this.associationsField;
            }
            set {
                this.associationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class PropertyDefinition : ValueDefinition {
        
        private bool mandatoryField;
        
        private bool readOnlyField;
        
        private string defaultValueField;
        
        public PropertyDefinition() {
            this.mandatoryField = false;
            this.readOnlyField = false;
        }
        
        /// <remarks/>
        public bool mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        public bool readOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
            }
        }
        
        /// <remarks/>
        public string defaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyDefinition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ValueDefinition {
        
        private string nameField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string dataTypeField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class AssociationDefinition {
        
        private string nameField;
        
        private string titleField;
        
        private string descriptionField;
        
        private bool isChildField;
        
        private RoleDefinition sourceRoleField;
        
        private RoleDefinition targetRoleField;
        
        private string targetClassField;
        
        public AssociationDefinition() {
            this.isChildField = true;
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool isChild {
            get {
                return this.isChildField;
            }
            set {
                this.isChildField = value;
            }
        }
        
        /// <remarks/>
        public RoleDefinition sourceRole {
            get {
                return this.sourceRoleField;
            }
            set {
                this.sourceRoleField = value;
            }
        }
        
        /// <remarks/>
        public RoleDefinition targetRole {
            get {
                return this.targetRoleField;
            }
            set {
                this.targetRoleField = value;
            }
        }
        
        /// <remarks/>
        public string targetClass {
            get {
                return this.targetClassField;
            }
            set {
                this.targetClassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class RoleDefinition {
        
        private string nameField;
        
        private Cardinality cardinalityField;
        
        public RoleDefinition() {
            this.cardinalityField = Cardinality.Item;
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(Cardinality.Item)]
        public Cardinality cardinality {
            get {
                return this.cardinalityField;
            }
            set {
                this.cardinalityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum Cardinality {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0..1")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("*")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1..*")]
        Item11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/repository/1.0")]
    public partial class UpdateResult {
        
        private string statementField;
        
        private ResultSet updateCountField;
        
        private Reference sourceField;
        
        private Reference destinationField;
        
        /// <remarks/>
        public string statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultSet updateCount {
            get {
                return this.updateCountField;
            }
            set {
                this.updateCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Reference source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Reference destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ResultSet {
        
        private ResultSetRow[] rowsField;
        
        private long totalRowCountField;
        
        private ResultSetMetaData metaDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rows")]
        public ResultSetRow[] rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
            }
        }
        
        /// <remarks/>
        public long totalRowCount {
            get {
                return this.totalRowCountField;
            }
            set {
                this.totalRowCountField = value;
            }
        }
        
        /// <remarks/>
        public ResultSetMetaData metaData {
            get {
                return this.metaDataField;
            }
            set {
                this.metaDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ResultSetRow {
        
        private long rowIndexField;
        
        private NamedValue[] columnsField;
        
        private float scoreField;
        
        private bool scoreFieldSpecified;
        
        private ResultSetRowNode nodeField;
        
        /// <remarks/>
        public long rowIndex {
            get {
                return this.rowIndexField;
            }
            set {
                this.rowIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("columns")]
        public NamedValue[] columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
        
        /// <remarks/>
        public float score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ResultSetRowNode node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResultSetRowNode {
        
        private string idField;
        
        private string typeField;
        
        private string[] aspectsField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aspects")]
        public string[] aspects {
            get {
                return this.aspectsField;
            }
            set {
                this.aspectsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ResultSetMetaData {
        
        private ValueDefinition[] valueDefsField;
        
        private ClassDefinition[] classDefsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valueDefs")]
        public ValueDefinition[] valueDefs {
            get {
                return this.valueDefsField;
            }
            set {
                this.valueDefsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classDefs")]
        public ClassDefinition[] classDefs {
            get {
                return this.classDefsField;
            }
            set {
                this.classDefsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Predicate {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nodes", typeof(Reference), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("query", typeof(Query), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("store", typeof(Store), IsNullable=true)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Query {
        
        private QueryLanguageEnum languageField;
        
        private string statementField;
        
        /// <remarks/>
        public QueryLanguageEnum language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum QueryLanguageEnum {
        
        /// <remarks/>
        lucene,
        
        /// <remarks/>
        xpath,
        
        /// <remarks/>
        cql,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CML {
        
        private CMLCreate[] createField;
        
        private CMLAddAspect[] addAspectField;
        
        private CMLRemoveAspect[] removeAspectField;
        
        private CMLUpdate[] updateField;
        
        private CMLDelete[] deleteField;
        
        private CMLMove[] moveField;
        
        private CMLCopy[] copyField;
        
        private CMLAddChild[] addChildField;
        
        private CMLRemoveChild[] removeChildField;
        
        private CMLCreateAssociation[] createAssociationField;
        
        private CMLRemoveAssociation[] removeAssociationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("create")]
        public CMLCreate[] create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addAspect")]
        public CMLAddAspect[] addAspect {
            get {
                return this.addAspectField;
            }
            set {
                this.addAspectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("removeAspect")]
        public CMLRemoveAspect[] removeAspect {
            get {
                return this.removeAspectField;
            }
            set {
                this.removeAspectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("update")]
        public CMLUpdate[] update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delete")]
        public CMLDelete[] delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("move")]
        public CMLMove[] move {
            get {
                return this.moveField;
            }
            set {
                this.moveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("copy")]
        public CMLCopy[] copy {
            get {
                return this.copyField;
            }
            set {
                this.copyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addChild")]
        public CMLAddChild[] addChild {
            get {
                return this.addChildField;
            }
            set {
                this.addChildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("removeChild")]
        public CMLRemoveChild[] removeChild {
            get {
                return this.removeChildField;
            }
            set {
                this.removeChildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("createAssociation")]
        public CMLCreateAssociation[] createAssociation {
            get {
                return this.createAssociationField;
            }
            set {
                this.createAssociationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("removeAssociation")]
        public CMLRemoveAssociation[] removeAssociation {
            get {
                return this.removeAssociationField;
            }
            set {
                this.removeAssociationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLCreate {
        
        private string idField;
        
        private ParentReference parentField;
        
        private string typeField;
        
        private NamedValue[] propertyField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public ParentReference parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public NamedValue[] property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLAddAspect {
        
        private string aspectField;
        
        private NamedValue[] propertyField;
        
        private Predicate whereField;
        
        private string where_idField;
        
        /// <remarks/>
        public string aspect {
            get {
                return this.aspectField;
            }
            set {
                this.aspectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public NamedValue[] property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        public Predicate @where {
            get {
                return this.whereField;
            }
            set {
                this.whereField = value;
            }
        }
        
        /// <remarks/>
        public string where_id {
            get {
                return this.where_idField;
            }
            set {
                this.where_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLRemoveAspect {
        
        private string aspectField;
        
        private Predicate whereField;
        
        private string where_idField;
        
        /// <remarks/>
        public string aspect {
            get {
                return this.aspectField;
            }
            set {
                this.aspectField = value;
            }
        }
        
        /// <remarks/>
        public Predicate @where {
            get {
                return this.whereField;
            }
            set {
                this.whereField = value;
            }
        }
        
        /// <remarks/>
        public string where_id {
            get {
                return this.where_idField;
            }
            set {
                this.where_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLUpdate {
        
        private NamedValue[] propertyField;
        
        private Predicate whereField;
        
        private string where_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public NamedValue[] property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        public Predicate @where {
            get {
                return this.whereField;
            }
            set {
                this.whereField = value;
            }
        }
        
        /// <remarks/>
        public string where_id {
            get {
                return this.where_idField;
            }
            set {
                this.where_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLDelete {
        
        private Predicate whereField;
        
        /// <remarks/>
        public Predicate @where {
            get {
                return this.whereField;
            }
            set {
                this.whereField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLMove {
        
        private ParentReference toField;
        
        private string to_idField;
        
        private string associationTypeField;
        
        private string childNameField;
        
        private Predicate whereField;
        
        private string where_idField;
        
        /// <remarks/>
        public ParentReference to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string to_id {
            get {
                return this.to_idField;
            }
            set {
                this.to_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
        public string associationType {
            get {
                return this.associationTypeField;
            }
            set {
                this.associationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
        public string childName {
            get {
                return this.childNameField;
            }
            set {
                this.childNameField = value;
            }
        }
        
        /// <remarks/>
        public Predicate @where {
            get {
                return this.whereField;
            }
            set {
                this.whereField = value;
            }
        }
        
        /// <remarks/>
        public string where_id {
            get {
                return this.where_idField;
            }
            set {
                this.where_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLCopy {
        
        private ParentReference toField;
        
        private string to_idField;
        
        private string associationTypeField;
        
        private string childNameField;
        
        private Predicate whereField;
        
        private string where_idField;
        
        private bool childrenField;
        
        public CMLCopy() {
            this.childrenField = false;
        }
        
        /// <remarks/>
        public ParentReference to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string to_id {
            get {
                return this.to_idField;
            }
            set {
                this.to_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
        public string associationType {
            get {
                return this.associationTypeField;
            }
            set {
                this.associationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
        public string childName {
            get {
                return this.childNameField;
            }
            set {
                this.childNameField = value;
            }
        }
        
        /// <remarks/>
        public Predicate @where {
            get {
                return this.whereField;
            }
            set {
                this.whereField = value;
            }
        }
        
        /// <remarks/>
        public string where_id {
            get {
                return this.where_idField;
            }
            set {
                this.where_idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLAddChild {
        
        private ParentReference toField;
        
        private string to_idField;
        
        private string associationTypeField;
        
        private string childNameField;
        
        private Predicate whereField;
        
        private string where_idField;
        
        /// <remarks/>
        public ParentReference to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string to_id {
            get {
                return this.to_idField;
            }
            set {
                this.to_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
        public string associationType {
            get {
                return this.associationTypeField;
            }
            set {
                this.associationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
        public string childName {
            get {
                return this.childNameField;
            }
            set {
                this.childNameField = value;
            }
        }
        
        /// <remarks/>
        public Predicate @where {
            get {
                return this.whereField;
            }
            set {
                this.whereField = value;
            }
        }
        
        /// <remarks/>
        public string where_id {
            get {
                return this.where_idField;
            }
            set {
                this.where_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLRemoveChild {
        
        private object itemField;
        
        private Predicate whereField;
        
        private string where_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("from", typeof(Reference))]
        [System.Xml.Serialization.XmlElementAttribute("from_id", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public Predicate @where {
            get {
                return this.whereField;
            }
            set {
                this.whereField = value;
            }
        }
        
        /// <remarks/>
        public string where_id {
            get {
                return this.where_idField;
            }
            set {
                this.where_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLCreateAssociation {
        
        private Predicate fromField;
        
        private string from_idField;
        
        private Predicate toField;
        
        private string to_idField;
        
        private string associationField;
        
        /// <remarks/>
        public Predicate from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string from_id {
            get {
                return this.from_idField;
            }
            set {
                this.from_idField = value;
            }
        }
        
        /// <remarks/>
        public Predicate to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string to_id {
            get {
                return this.to_idField;
            }
            set {
                this.to_idField = value;
            }
        }
        
        /// <remarks/>
        public string association {
            get {
                return this.associationField;
            }
            set {
                this.associationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CMLRemoveAssociation {
        
        private Predicate fromField;
        
        private string from_idField;
        
        private Predicate toField;
        
        private string to_idField;
        
        private string associationField;
        
        /// <remarks/>
        public Predicate from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string from_id {
            get {
                return this.from_idField;
            }
            set {
                this.from_idField = value;
            }
        }
        
        /// <remarks/>
        public Predicate to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string to_id {
            get {
                return this.to_idField;
            }
            set {
                this.to_idField = value;
            }
        }
        
        /// <remarks/>
        public string association {
            get {
                return this.associationField;
            }
            set {
                this.associationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/repository/1.0")]
    public partial class Association {
        
        private string associationTypeField;
        
        private AssociationDirectionEnum directionField;
        
        /// <remarks/>
        public string associationType {
            get {
                return this.associationTypeField;
            }
            set {
                this.associationTypeField = value;
            }
        }
        
        /// <remarks/>
        public AssociationDirectionEnum direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/repository/1.0")]
    public enum AssociationDirectionEnum {
        
        /// <remarks/>
        source,
        
        /// <remarks/>
        target,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/repository/1.0")]
    public partial class QueryResult {
        
        private string querySessionField;
        
        private ResultSet resultSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string querySession {
            get {
                return this.querySessionField;
            }
            set {
                this.querySessionField = value;
            }
        }
        
        /// <remarks/>
        public ResultSet resultSet {
            get {
                return this.resultSetField;
            }
            set {
                this.resultSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void createStoreCompletedEventHandler(object sender, createStoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createStoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createStoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Store Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Store)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getStoresCompletedEventHandler(object sender, getStoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Store[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Store[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void queryCompletedEventHandler(object sender, queryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void queryChildrenCompletedEventHandler(object sender, queryChildrenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void queryParentsCompletedEventHandler(object sender, queryParentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryParentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryParentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void queryAssociatedCompletedEventHandler(object sender, queryAssociatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryAssociatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryAssociatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void fetchMoreCompletedEventHandler(object sender, fetchMoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchMoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchMoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void describeCompletedEventHandler(object sender, describeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class describeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal describeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NodeDefinition[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NodeDefinition[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getCompletedEventHandler(object sender, getCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Node[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Node[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591