#!/bin/sh
export JAVA_OPTS='-Xms128m -Xmx512m -XX:MaxPermSize=128m -server'
cd "@@ALF_HOME@@"
sh ./tomcat/bin/startup.sh
while [ ! -s "@@ALF_HOME@@/tomcat/logs/catalina.out" ]
  do
  printf "%10s \r" "waiting for log to be created..."
  sleep 1
done
tail -f "@@ALF_HOME@@/tomcat/logs/catalina.out"
