#!/bin/sh
export JAVA_OPTS='-Xms512m -Xmx1024m -Xss1024k -XX:MaxPermSize=256m -XX:NewSize=256m -server'
export JAVA_OPTS="${JAVA_OPTS} -Dalfresco.home=${ALF_HOME} -Dcom.sun.management.jmxremote"
cd "@@ALF_HOME@@"
sh ./tomcat/bin/startup.sh
while [ ! -s "@@ALF_HOME@@/tomcat/logs/catalina.out" ]
  do
  printf "%10s \r" "waiting for log to be created..."
  sleep 1
done
tail -f "@@ALF_HOME@@/tomcat/logs/catalina.out"
