;/* Version e39ae1f2afb7bb0faad24cf476d8250e v:3.8.5.1, c:1f3de918596a9cbfaa3eae444ae1f12fc9befc5b, b:4805 n:12-3.8.5.next */(function(){var e=!0,h=null,j=!1;
if(!(window.ADRUM||window["adrum-disable"]===e)){window["adrum-start-time"]=window["adrum-start-time"]||(new Date).getTime();var m="https:"===document.location.protocol;if(window["adrum-geo-resolver-url"]){var t=window["adrum-geo-resolver-url"],u=t.indexOf("://");-1!=u&&(t=t.substring(u+3));t=(m?"https://":"http://")+t}else t=m?"":"";window.ADRUM={beaconUrlHttp:"http://col.eum-appdynamics.com",beaconUrlHttps:"https://col.eum-appdynamics.com",appKey:window["adrum-app-key"]||"AD-AAB-AAA-GZW",
adrumExtUrl:(m?"https://de8of677fyt0b.cloudfront.net":"http://de8of677fyt0b.cloudfront.net")+"/adrum-ext.e39ae1f2afb7bb0faad24cf476d8250e.js",geoResolverUrl:t,useStrictDomainCookies:window["adrum-use-strict-domain-cookies"]===e,TPL:{}};"APP_KEY_NOT_SET"===window.ADRUM.appKey&&"undefined"!==typeof console&&"undefined"!==typeof console.log&&console.log("AppDynamics EUM cloud application key missing. Please specify window['adrum-app-key']");var v=window.ADRUM;v.TPL.Qa=function(d){return 0<=d.location.search.indexOf("ADRUM_debug=true")||
0<=d.cookie.search(/(^|;)\s*ADRUM_debug=true/)};v.TPL.iDR=v.TPL.Qa;v.isDebug=v.TPL.Qa(document);v.TPL.ia=100;v.logMessages=[];for(var w=["debug","warn","info","error"],y=0;y<w.length;y++)(function(d){v[d]=function(n,s){v.isDebug&&v.logMessages.push([d,Array.prototype.slice.call(arguments).join(" | ")])}})(w[y]);var z=0;v.TPL.N=function(d,n,s,f){d=s+"/eumcollector/error.gif?version=1&appKey="+f+"&msg="+encodeURIComponent(d.substring(0,500));n&&(d+="&stack=",d+=encodeURIComponent(n.substring(0,1500-
d.length)));return d};v.TPL.cIEBU=v.TPL.N;v.TPL.j=function(d,n){2<=z||((new Image).src=v.TPL.N(d,n,v.beaconUrlHttps,v.appKey),z++)};var A=v.error;v.error=function(){if(0<arguments.length){var d=Array.prototype.slice.call(arguments).join(" | ");A(d);v.TPL.j(d,h)}};v.exception=function(){if(!(1>arguments.length)){var d=Array.prototype.slice.call(arguments),n;(n=d[0])?(n=n.stack,n=!n||"string"!==typeof n?h:n):n=h;d=d.slice(1).join(" | ");A(d);v.TPL.j(d,n)}};v.assert=function(d,n){d||v.error("Assert fail: "+
n)};v.isDebug&&(v.TPL.dumpLog=function(){for(var d="",n=0;n<v.logMessages.length;n++)var s=v.logMessages[n],d=d+("["+s[0]+"]\t"+s[1].replace(RegExp("<br/>","g"),"\n\t")+"\n");return d});v.info("M0");v.addEventListener=function(d,n,s){function f(){try{return s.apply(this,Array.prototype.slice.call(arguments))}catch(f){v.exception(f,"M2",n,d,f)}}v.isDebug&&v.debug("M1",n,d);d.addEventListener?d.addEventListener(n,f,j):d.attachEvent&&d.attachEvent("on"+n,f)};v.compareWindows=function(d,n){return d==
n};v.TPL.p=function(d,n){function s(d){v.debug("M4",d);var n=new Date;n.setTime(n.getTime()-1E3);document.cookie=d+"=;Expires="+n.toGMTString()}v.info("M3");for(var f=/^\s*ADRUM=s=([\d]+)&r=(.*)\s*/,g=n?n.length:0,l=/^\s*(ADRUM_(\d+)_(\d+)_(\d+))=(.*)\s*$/i,k=[],p=d.split(";"),q=0;q<p.length;q++){var x=p[q],r;a:{if(r=l.exec(x)){var B=r[1],I=r[4],E=r[5];if(Number(r[3])===g){s(B);r=[Number(I),E];break a}}r=h}if(r)k.push(r);else if(r=f.exec(x))v.debug("M5",x),3===r.length?(v.startTimeCookie={startTime:Number(r[1]),
startPage:r[2]},s("ADRUM")):v.error("M6",x)}Array.prototype.sort.call(k,function(d,n){return d[0]-n[0]});f=[];for(q=0;q<k.length;q++)f.push(k[q][1]);k=/^\s*(ADRUM_BT)=(.*)\s*$/i;for(q=0;q<p.length;q++){l=[];if(r=k.exec(p[q]))if(x=r[1],r=r[2].replace(/^"|"$/g,""),r=decodeURIComponent(r).split("|"),B=r[0].split(":"),"R"===B[0]&&Number(B[1])===g){s(x);for(x=1;x<r.length;x++)l.push(r[x])}l&&0<l.length&&(f=f.concat(l))}v.cookieMetadataChunks=f};v.TPL.p(document.cookie,document.referrer);v.TPL.eck=v.TPL.p;
v.q=[];v.isDead=j;v.command=function(d,n){v.isDebug&&v.debug("M7",d,Array.prototype.slice.call(arguments).slice(1).join(", "));v.isDead?v.debug("M8"):v.q.length>=v.TPL.ia?(v.info("M9"),v.q=[],v.isDead=e):(v.q.push(Array.prototype.slice.call(arguments)),v.processQ&&v.processQ())};v.command("mark","firstbyte",window["adrum-start-time"]);v.TPL.m={C:function(d){return!d||"apply"in d},h:function(d,n,s,f){v.assert(this.C(d),"M10");n=n||function(){};d=d||function(){};s=s||function(){};return function(){v.isDebug&&
v.debug("M11",f,Array.prototype.slice.call(arguments).join(", "));var g=Array.prototype.slice.call(arguments),l;try{l=n.apply(this,g)}catch(k){v.exception(k,"M12",f,k)}v.assert(!l||"[object Array]"===Object.prototype.toString.call(l));var p=void 0;try{p=d.apply(this,l||g)}finally{try{s.apply(this,g)}catch(q){v.exception(q,"M13",f,q)}}return p}}};var D=function(){this.Aa=[];this.ca(C,0)},C="AFTER_FIRST_BYTE";D.prototype.Ga=[C,"AFTER_DOM_INTERACTIVE","AT_ONLOAD","AFTER_ONLOAD"];D.prototype.Y=function(d){this.ca("AFTER_DOM_INTERACTIVE",
d)};D.prototype.ua=function(d){this.ca("AT_ONLOAD",d)};D.prototype.Z=function(d){this.ca("AFTER_ONLOAD",d)};D.prototype.ca=function(d,n){this.Aa.push({Nb:(new Date).getTime(),Mb:n,ba:d});this.ba=d};D.prototype.getPhaseID=function(d){for(var n=0;n<this.Ga.length;n++)if(this.Ga[n]==d)return n;return h};D.prototype.getPhaseCallbackTime=function(d){for(var n=this.Aa,s=0;s<n.length;s++)if(n[s].ba==d)return n[s].Nb;return h};D.prototype.findPhaseAtNominalTime=function(d){v.assert(0<=d);for(var n=this.Aa,
s=n.length-1;0<=s;s--)if(d>=n[s].Mb)return n[s].ba;v.error("M14",d,v.EXT.La(n));return C};v.lifecycle=new D;v.TPL.oa=D;var F=j;v.listenForErrors=function(){v.TPL.m.C(window.onerror)?(window.onerror=v.TPL.m.h(window.onerror,function(d,n,s){F||v.command("reportError",d,n,s);F=e},function(){F=j},"onerror"),v.windowErrorHandler=window.onerror,v.info("M15")):v.info("M16")};v.listenForErrors();v.addEventListener(window,"load",function(d){v.lifecycle.ua(d&&d.timeStamp);setTimeout(function(){var d=(new Date).getTime();
v.lifecycle.Z(d);v.command("mark","onload",d);v.navTiming=h;if((d=window.performance||window.a||window.b||window.c)&&d.timing)if(d=d.timing,d.navigationStart&&d.navigationStart<=d.loadEventEnd){var s={},f;for(f in d){var g=d[f];"number"===typeof g&&(s[f]=g)}v.navTiming=s}else v.debug("M43");v.command("reportOnload");f=document.createElement("script");f.async=e;f.src=v.adrumExtUrl;(d=document.getElementsByTagName("script")[0])?(d.parentNode.insertBefore(f,d),v.info("M44")):v.info("M45")},0);v.info("M17")});
var G=j,J=function(d){G||(v.lifecycle.Y(d&&d.timeStamp),v.command("mark","onready",(new Date).getTime()),G=e)},K=function(d){document.addEventListener?(document.removeEventListener("DOMContentLoaded",K,j),J(d)):"complete"===document.readyState&&(document.detachEvent("onreadystatechange",K),J(d))};if(document.addEventListener)document.addEventListener("DOMContentLoaded",K,j),window.addEventListener("load",J,j);else{document.attachEvent("onreadystatechange",K);window.attachEvent("onload",J);var L=j;
try{L=window.frameElement==h&&document.documentElement}catch(N){}L&&L.doScroll&&function O(){try{L.doScroll("left")}catch(n){setTimeout(O,10);return}J()}()}v.info("M18");if(window["adrum-xhr-disable"]===e)v.info("M19");else if(window.XMLHttpRequest){var P=window.XMLHttpRequest.prototype;if(P)if("open"in P&&"send"in P)if(!v.TPL.m.C(P.open)||!v.TPL.m.C(P.send))v.info("M23");else{v.info("M24");var Q=function(d){var n=d._adrumXhrData;if(n){var s=(new Date).getTime();2==d.readyState?n.firstByteTime=n.firstByteTime||
s:4==d.readyState&&(v.assert(n.respAvailTime===h,"M25"),n.respAvailTime=n.respAvailTime||s,n.firstByteTime=n.firstByteTime||s)}},R=function(d,n){var s=d.getAllResponseHeaders(),f=d.status;v.command("reportXhr",n,s,f,400<=f?d.responseText:h)},S=function(d,n,s){var f=d;d&&("object"===typeof d&&"toString"in d&&"[xpconnect wrapped nsIDOMEventListener]"===d.toString()&&"handleEvent"in d)&&(f=function(){d.handleEvent.apply(this,Array.prototype.slice.call(arguments))});return v.TPL.m.h(f,function(){Q(this)},
function(){var d=n._adrumXhrData;if(d&&4==n.readyState){var s=(new Date).getTime();v.assert(d.respProcTime===h,"M26");d.respProcTime=d.respProcTime||s;R(n,d);delete n._adrumXhrData}},s)},T=function(d){if(d._adrumXhrData){var n=(new Date).getTime()+3E4,s=function(){Q(d);var f=d._adrumXhrData;if(f){var g=(new Date).getTime();4==d.readyState?(v.assert(f.respProcTime===h,"M27"),f.respProcTime=f.respProcTime||g,v.debug("M28"),R(d,f),delete d._adrumXhrData):g<n?setTimeout(s,50):(delete d._adrumXhrData,
v.debug("M29"))}};s()}};P.open=v.TPL.m.h(P.open,function(){this._adrumXhrData={url:2<=arguments.length?String(arguments[1]):"",sendTime:h,firstByteTime:h,respAvailTime:h,respProcTime:h,parentPhase:h}},h,"XHR.open");P.send=v.TPL.m.h(P.send,function(){var d=this,n=d._adrumXhrData;if(n){var s=(new Date).getTime();v.assert(n.sendTime===h,"M30");n.sendTime=n.sendTime||s;n.parentPhase=v.lifecycle.ba;var f=n.url,s=document.createElement("a");s.href=f;f=document.location;":"===s.protocol&&""===s.hostname&&
""===s.port||s.protocol===f.protocol&&s.hostname===f.hostname&&s.port===f.port?d.setRequestHeader("ADRUM","isAjax:true"):v.debug("M31",document.location.href,n.url);var g=0,l=function(){if(4==d.readyState)v.debug("M32"),T(d);else{var n=h;try{n=d.onreadystatechange}catch(s){v.debug("M33",s);T(d);return}g++;n?v.TPL.m.C(n)?(d.onreadystatechange=S(n,d,"XHR.onReadyStateChange"),v.debug("M34",g)):(v.debug("M35"),T(d)):5>g?setTimeout(l,0):(v.debug("M36"),T(d))}};l()}},h,"XHR.send");var U="addEventListener"in
P&&"removeEventListener"in P&&v.TPL.m.C(P.addEventListener)&&v.TPL.m.C(P.removeEventListener);v.TPL.Ja=function(){return function(d,n){if(!("load"!==d&&"error"!==d)&&n&&this._adrumXhrData){var s;s=n;if(s.__adrumInterceptor)s=s.__adrumInterceptor;else if(v.TPL.m.C(s)){var f=S(s,this,"XHR.invokeEventListener");s=s.__adrumInterceptor=f}else s=h;if(s)return f=Array.prototype.slice.call(arguments),f[1]=s,v.debug("M37"),f;v.debug("M38",d,n)}}};U?(P.addEventListener=v.TPL.m.h(P.addEventListener,v.TPL.Ja(),
h,"XHR.addEventListener"),P.removeEventListener=v.TPL.m.h(P.removeEventListener,function(d,n){if(this._adrumXhrData){var s=Array.prototype.slice.call(arguments);n.__adrumInterceptor?(s[1]=n.__adrumInterceptor,v.debug("M39")):v.debug("M40");return s}},h,"XHR.removeEventListener")):v.debug("M41");v.info("M42")}else v.info("M22");else v.info("M21")}else v.info("M20")};})();

