-- phpMyAdmin SQL Dump
-- version 3.3.9.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 08, 2011 at 03:16 PM
-- Server version: 5.5.9
-- PHP Version: 5.3.6

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `drupal`
--

-- --------------------------------------------------------

--
-- Table structure for table `alf_blacklist`
--

CREATE TABLE alf_blacklist (
   id int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key: Unique blocked domain ID.',
   domain varchar(64) NOT NULL COMMENT 'Blocked Email Domain.',
   type varchar(11) NOT NULL DEFAULT 'ANTISPAM' COMMENT 'Type of blocked email domain: PUBLIC, ANTISPAM, BLACKLISTED.',
   note text COMMENT 'Optional note on why domain was blacklisted.',
   PRIMARY KEY (id),
   UNIQUE INDEX idx_alf_bll_dom (domain)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='Stores list of email domains blocked from signing up for...' AUTO_INCREMENT=4 ;

--
-- Dumping data for table `alf_blacklist`
--

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('antispam.test', 'ANTISPAM', 'a note');
INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('blacklisted.test', 'BLACKLISTED', 'This was blacklisted at request of dfdfdf@sfsds.com');
INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('public.test', 'PUBLIC', 'public domain for Alfresco test purposes');


-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('123mail.org','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('138mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('150mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('150ml.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('163.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('16mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('2-mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('2die4.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('4email.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('50mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('abbeysorchids.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('abha.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('accountant.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('acdcfan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('activist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('adam.com.au','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('adexec.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('africamail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ahsa.ws','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('aircraftmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('airpost.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ajman.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ajman.us','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ajman.ws','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('alabama.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('alaska.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('albaha.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('alex4all.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('alexandria.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('allergist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('allmail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('alriyadh.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('alumni.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('alumnidirector.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('americamail.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('amorous.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('angelic.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('animail.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('anonymbox.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('aol.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('aon.at','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('appraiser.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('arar.ws','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('archaeologist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('arcticmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('arizona.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('arkansas.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('aroma.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('artlover.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('asia-mail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('asia.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('asiamail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('aswan.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('atheist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('att.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('auctioneer.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('aussiemail.com.au','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('australiamail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('barhams.co.uk','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('bartender.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('been-there.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('bellair.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('bellsouth.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('berlin.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('bestmail.us','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('bigger.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('bikerider.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('binkmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('birdlover.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('blader.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('bluebottle.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('boardermail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('bobmail.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('brazilmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('brew-master.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('brew-meister.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('bsdmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('btinternet.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('buraydah.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('california.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('californiamail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cameroon.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('canada.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('canoemail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('car-seats-baby.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('caress.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cash4u.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('catlover.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('chammy.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('chase.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('chasepaymentech.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cheerful.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('chef.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('chemist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('chicagohairsalon.info','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('chinamail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('clerk.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cliffhanger.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('clubmember.org','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cluemail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('collector.org','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('colorado.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('columnist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('comcast.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('comcast.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('comfortable.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('comic.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('computer4u.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('connecticut.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('consultant.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('contractor.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cool.fr.nf','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('coolsite.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('counsellor.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('count.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('couple.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('courriel.fr.nf','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cox.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('csaa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cust.in','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cutey.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cyber-wizard.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cyberclicksolutions.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cyberdude.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cybergal.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('cyberservices.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('DaCoolest.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dallasmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dbzmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dcemail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('delaware.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('delhimail.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('deliveryman.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dhahran.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('didamail.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('diplomats.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('directbox.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('discardmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('discardmail.de','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('disciples.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('discofan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('disposable.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dispostable.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('djibouti.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('doctor.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dodgeit.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dodgit.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('doglover.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dominican.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('doramail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('doubt.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dr.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dublin.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('dutchmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('earthling.net','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('eastlink.ca','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('elitemail.org','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('elvisfan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('email.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('emailaccount.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('emailcorner.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('emailengine.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('emailengine.org','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('emailgroups.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('emailplus.org','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('emailuser.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('eml.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('empal.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('engineer.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('englandmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('eritrea.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('europe.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('europemail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('execs.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('f-m.fm','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('facebook.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fan.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fan.net','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fast-email.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fast-mail.org','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastem.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastemail.us','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastemailer.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastermail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastest.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastimap.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.cn','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.co.uk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.com.au','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.es','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.fm','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.in','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.jp','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.to','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmail.us','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmailbox.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastmessaging.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fastservice.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fea.st','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('feelings.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('financier.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fireman.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('firstusa.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('florida.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fmail.co.uk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fmailbox.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fmgirl.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fmguy.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('footballer.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('formulaoneworld.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fr33mail.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('free.fr','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ftml.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fujairah.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('fujairah.ws','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('gardener.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('garfield.in','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('geologist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('germanymail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('giza.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('gmail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('gmx.de','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('googlemail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('graduate.org','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('graffiti.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('graphic-designer.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('greenmail.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('groupmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('guerrillamail.org','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('guinea.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('h-mail.us','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hackermail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hailmail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hairdresser.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hanmail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hasakah.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hebron.tv','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hilarious.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hiphopfan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hochsitze.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hockeymail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('homemail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('homosexual.net','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('homs.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hot-shot.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.co.il','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.co.jp','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.co.th','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.co.uk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.com.ar','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.com.br','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.com.tr','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.de','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.es','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.fr','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.it','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.jp','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotmail.se','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hotpop.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hour.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('housemail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('howling.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hulapla.de','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('humanoid.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hush.ai','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hush.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('hushmail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('husmail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ibra.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('icqmail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('idaho.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('illinois.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('imails.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('imap-mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('imap.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('imapmail.org','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('in.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('iname.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('inboxclean.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('indiamail.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('indiana.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('indiatimes.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('innocent.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('inorbit.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('inoutbox.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('instruction.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('instructor.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('insurer.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('internet-e-mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('internet-mail.org','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('internetemails.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('internetmailing.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('iowa.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('irbid.ws','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('irelandmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('israelmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('italymail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ittelligence.co.za','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ive.no','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('japan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('jetable.fr.nf','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('jetemail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('jizan.cc','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('job4u.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('jouf.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('journalist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('jpmchase.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('jpmorgan.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('jpmorgancazenove.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('jrexx.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('Junk1e.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('justemail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('kansas.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('keromail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('khartoum.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('khobar.cc','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('kissfans.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('kittymail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('korea.kr','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('koreamail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('koreanmail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('kpnmail.nl','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('kurzepost.de','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('kuwaiti.tv','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('kyrgyzstan.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('laposte.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('lavabit.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('lawyer.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('lebanese.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('legislator.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('letterboxes.org','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('linuxmail.org','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.at','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.be','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.ca','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.cl','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.cn','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.co','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.co.kr','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.co.uk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.co.za','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.com.ar','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.com.au','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.com.bd','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.com.mx','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.com.my','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.com.ph','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.com.pt','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.com.sg','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.de','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.dk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.fi','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.fr','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.hk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.ie','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.in','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.it','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.jp','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.nl','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.ph','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.ru','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('live.se','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('lls.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('lobbyist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('london.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('louisiana.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('loveable.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('lovecat.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('lpemail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('lubnan.ws','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('lycos.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('m4ilweb.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mac.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mad.scientist.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('madinah.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('madonnafan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('madrid.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('maghreb.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail-central.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail-me.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail-page.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail.google.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail.org','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail.rakuten.co.jp','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail2net.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail2web.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mailforspam.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mailinator.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mailinator.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('makrani.biz','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('marchmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mchsi.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('me.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mega.zik.dj','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('meowmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('metalfan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mexicomail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mezimages.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('minister.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('moncourrier.fr.nf','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('monemail.fr.nf','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('monmail.fr.nf','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('moscowmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('moviesblaster.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('msnhotmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('munich.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('musician.org','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('muslim.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mymailindex.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mypartyclip.de','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('myself.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('myspace.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('namesplace.net','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('nate.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('naver.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('net-shopping.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ninfan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('nomail.xl.cx','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('nonpartisan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('nospam.ze.tc','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('nospamthanks.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('null.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('nycmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('oath.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('objectmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('oneequity.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('optician.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('orthodontist.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('otherinbox.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('pacific-ocean.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('pacificwest.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('paran.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('pediatrician.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('petlover.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('photographer.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('physicist.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('pjjkp.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('planetmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('planetmail.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('polandmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('politician.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('politikerclub.de','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('post.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('presidency.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('pricepickle.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('priest.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('programmer.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('protestant.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('providian.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('proxymail.eu','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('publicist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('qq.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('qualityservice.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rabat.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('radiologist.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ramallah.cc','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ravemail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rcpt.at','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('realemail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('reallyfast.biz','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('reallyfast.info','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('realtyagent.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('reborn.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rediffmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('reggaefan.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('registerednurses.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('reincarnate.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('religious.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('repairman.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('representative.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rescueteam.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('revenue.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rhodeisland.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('roadrunner.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rocketmail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rocketship.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rockfan.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rogers.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rome.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('royal.net','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rushpost.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('russiamail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('s0ny.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('safat.info','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('safe-mail.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('safetymail.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('safrica.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('saintly.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('salesperson.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('salmiya.biz','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('samerica.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sandiego.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sanfranmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sbcglobal.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('scientist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('scotlandmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('secretary.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('securitycapital.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('selkblog.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sent.as','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sent.at','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sent.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sfax.ws','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sharm.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sina.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('singapore.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('siria.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sizzling.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('snail-mail.net','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('snakebite.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('socialworker.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sociologist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('solution4u.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('songwriter.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('soon.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('southcarolina.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('southdakota.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('spainmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('spambog.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('spambog.de','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('spambog.ru','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('spamgourmet.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('speed.1s.fr','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('speedpost.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('speedymail.org','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sprint.blackberry.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ssl-mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('stalag13.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sudanese.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('suez.cc','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('suremail.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('surfy.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('surgical.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('swedenmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('swift-mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('swissmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sympatico.ca','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tabouk.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tajikistan.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tangiers.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tanta.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tayef.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('teachers.org','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tech-center.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('techie.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('technologist.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('teewars.org','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tempinbox.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tempting.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tennessee.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('texas.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('thanksnospam.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('the-fastest.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('thedays.ws','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('theplate.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('therapist.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('thisisnotmyrealemail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ThrowawayEmailAddress.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tmo.blackberry.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('toke.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tokyo.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('toothfairy.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('torontomail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tough.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tradermail.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('trash-mail.at','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('trash-mail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('trashmail.at','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('trashmail.me','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('trashmail.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tunisian.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('tvstar.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('umpire.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('uol.com.br','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('upcmail.nl','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('urdun.cc','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ureach.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('utah.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('utey.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('uymail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('vermont.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('veryfast.biz','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('veryspeedy.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('vfemail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('vfemail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wallet.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wamu.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wapicode.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('warpmail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('washington.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('webm4il.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('webmail.co.za','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('webname.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('weekonline.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wegwerfmail.de','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wegwerfmail.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wegwerfmail.org','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('weirdness.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('westvirginia.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('whale-mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('who.net','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('whoever.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wildmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wilemail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('windowslive.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('winning.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wisconsin.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('witty.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('worker.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('workmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('writeme.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('wyoming.usa.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('xsmail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('xtra.co.nz','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('y7mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.ca','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.cn','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.co.id','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.co.in','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.co.jp','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.co.uk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.ar','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.br','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.cn','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.hk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.in','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.mx','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.my','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.ph','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.sg','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.tw','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.com.vn','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.es','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.fr','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.in','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.qr','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yammer.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yanbo.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yepmail.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ymail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yopmail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yopmail.fr','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yopmail.net','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('your-mail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yours.com','BLACKLISTED','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yyhmail.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('zambia.cc','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('zenbe.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('zippymail.info','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('inbox.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('mail.ru','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('sneakemail.com','ANTISPAM','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('foo.com','BLACKLISTED','Some users using this for testing but not valid domain');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('rocketmail.co.uk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ymail.co.uk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('virginmedia.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('blueyonder.co.uk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('ntlworld.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('virgin.net','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('msn.com','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('msn.co.uk','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('gmail.cm','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('yahoo.it','PUBLIC','');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('microsoft.com','BLACKLISTED','Blocked until we fix transformation service');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('microsoft.co.uk','BLACKLISTED','Blocked until we fix transformation service');

INSERT INTO alf_blacklist (`domain`,`type`,`note`) VALUES ('inbox.ru','PUBLIC','');

