package org.alfresco.service.cmr.dictionary;

import org.alfresco.api.AlfrescoPublicApi;   
import org.alfresco.error.AlfrescoRuntimeException;

/**
 * Base Exception of Data Dictionary Exceptions.
 * 
 * @author David Caruana
 */
@AlfrescoPublicApi
public class DictionaryException extends AlfrescoRuntimeException
{
    private static final long serialVersionUID = 3257008761007847733L;

    public DictionaryException(String msgId)
    {
       super(msgId);
    }
    
    public DictionaryException(String msgId, Throwable cause)
    {
       super(msgId, cause);
    }

    public DictionaryException(String msgId, Object ... args)
    {
        super(msgId, args);
    }

    public DictionaryException(String msgId, Throwable cause, Object ... args)
    {
        super(msgId, args, cause);
    }

    /**
     * Exception generated by attempting to create a duplicate definition of the
     * data dictionary, such as type, aspect, constraint and etc.
     *
     * @author Jamal Kaabi-Mofrad
     */
    @AlfrescoPublicApi
    public static class DuplicateDefinitionException extends DictionaryException
    {
        private static final long serialVersionUID = -2623179649246011966L;

        public DuplicateDefinitionException(String msgId)
        {
            super(msgId);
        }

        public DuplicateDefinitionException(String msgId, Throwable cause)
        {
            super(msgId, cause);
        }

        public DuplicateDefinitionException(String msgId, Object... args)
        {
            super(msgId, args);
        }

        public DuplicateDefinitionException(String msgId, Throwable cause, Object... args)
        {
            super(msgId, cause, args);
        }
    }
}
