/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alfresco_jlan_netbios_win32_Win32NetBIOS */

#ifndef _Included_org_alfresco_jlan_netbios_win32_Win32NetBIOS
#define _Included_org_alfresco_jlan_netbios_win32_Win32NetBIOS
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alfresco_jlan_netbios_win32_Win32NetBIOS_FindNameBufferLen
#define org_alfresco_jlan_netbios_win32_Win32NetBIOS_FindNameBufferLen 33L
/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    AddName
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_AddName
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    AddGroupName
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_AddGroupName
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    FindNameRaw
 * Signature: (I[B[BI)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_FindNameRaw
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    DeleteName
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_DeleteName
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    LanaEnum
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_LanaEnum
  (JNIEnv *, jclass);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    Reset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_Reset
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    Listen
 * Signature: (I[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_Listen
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    Receive
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_Receive
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    Send
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_Send
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    SendDatagram
 * Signature: (II[B[BII)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_SendDatagram
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    SendBroadcastDatagram
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_SendBroadcastDatagram
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    ReceiveDatagram
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_ReceiveDatagram
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    ReceiveBroadcastDatagram
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_ReceiveBroadcastDatagram
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    Hangup
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_Hangup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    GetLocalNetBIOSName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_GetLocalNetBIOSName
  (JNIEnv *, jclass);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    GetLocalDomainName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_GetLocalDomainName
  (JNIEnv *, jclass);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    getWINSServerList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_getWINSServerList
  (JNIEnv *, jclass);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    InitializeSockets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_InitializeSockets
  (JNIEnv *, jclass);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    ShutdownSockets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_ShutdownSockets
  (JNIEnv *, jclass);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    CreateSocket
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_CreateSocket
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    CreateDatagramSocket
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_CreateDatagramSocket
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    BindSocket
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_BindSocket
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    ListenSocket
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_ListenSocket
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    CloseSocket
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_CloseSocket
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    SendSocket
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_SendSocket
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    ReceiveSocket
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_ReceiveSocket
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    SendSocketDatagram
 * Signature: (I[B[BII)I
 */
JNIEXPORT jint JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_SendSocketDatagram
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     org_alfresco_jlan_netbios_win32_Win32NetBIOS
 * Method:    waitForNetworkAddressChange
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alfresco_jlan_netbios_win32_Win32NetBIOS_waitForNetworkAddressChange
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
